apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kaboom-games
  namespace: argocd
spec:
  destination:
    namespace: kaboom-games
    server: 'https://kubernetes.default.svc'
  project: kaboom-games
  source:
    repoURL: 'https://github.com/toleksa/kaboom-games'
    targetRevision: 'HEAD'
    helm:
      values: |
        ingress:
          enabled: true
          hostname: "{{ .Values.website }}.{{ .Values.domain }}"
        service:
          type: ClusterIP
        metrics:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

